# config.yml
# Linux Users: PHP Namespaces use back slash \ rather than a forward slash /
# So for destinations_php, the namespace would be TestNs\MyApp
# $ vendor/bin/xsd2php convert config.yml sepxml/srvRefund0.xsd

xsd2php:
  namespaces:
    'http://tempuri.org/': 'Sep\Calculator'
    'http://schemas.datacontract.org/2004/07/Refund.DTO': 'Sep\IsrvRefund'
    'http://schemas.microsoft.com/2003/10/Serialization/': 'Sep\Serialization'
  destinations_php:
    'Sep\Calculator': src/Calculator
    'Sep\IsrvRefund': src/IsrvRefund
    'Sep\Serialization': src/Serialization
  destinations_jms:
    'Sep\Calculator': metadata/Calculator
    'Sep\IsrvRefund': metadata/IsrvRefund
    'Sep\Serialization': metadata/Serialization