# config.yml
# Linux Users: PHP Namespaces use back slash \ rather than a forward slash /
# So for destinations_php, the namespace would be TestNs\MyApp
# $ vendor/bin/xsd2php convert config.yml sepxml/srvRefund0.xsd

xsd2php:
  namespaces:
    'http://tempuri.org/': 'Calculator\Sep'
    'http://schemas.datacontract.org/2004/07/Refund.DTO': 'IsrvRefund\Sep'
    'http://schemas.microsoft.com/2003/10/Serialization/': 'Serialization\Sep'
  destinations_php:
    'Calculator\Sep': src/Calculator
    'IsrvRefund\Sep': src/IsrvRefund
    'Serialization\Sep': src/Serialization
  destinations_jms:
    'Calculator\Sep': metadata/Calculator
    'IsrvRefund\Sep': metadata/IsrvRefund
    'Serialization\Sep': metadata/Serialization