# config.yml
# Linux Users: PHP Namespaces use back slash \ rather than a forward slash /
# So for destinations_php, the namespace would be TestNs\MyApp
# $ vendor/bin/xsd2php convert config.yml sepxml/srvRefund0.xsd

xsd2php:
  namespaces:
    'http://tempuri.org/': 'Calculator'
    'http://schemas.datacontract.org/2004/07/Refund.DTO': 'IsrvRefund'
    'http://schemas.microsoft.com/2003/10/Serialization/': 'Serialization'
  destinations_php:
    'Calculator': src/Calculator
    'IsrvRefund': src/IsrvRefund
    'Serialization': src/Serialization
  destinations_jms:
    'Calculator': metadata/Calculator
    'IsrvRefund': metadata/IsrvRefund
    'Serialization': metadata/Serialization